name = "andrzej"
license = "CC0"
licenselink = "https://github.com/unjello/hugo-andrzej-theme/blob/master/LICENSE"
description = "Homepage theme for my personal page"
homepage = "https://andrzej.lichnerowicz.pl/"
tags = ["hugo", "personal"]
features = []
min_version = "0.41.0"

[author]
  name = "Andrzej Lichnerowicz"
  homepage = "https://andrzej.lichnerowicz.pl"



